name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Set up Git
        run: |
          git config --global user.email "myweb@ziegler.zip"
          git config --global user.name "Derek"
          
      - name: Build the file
        run: |
          npm install
          npm version --allow-same-version --git-tag-version=true --commit-hooks=false "${{ github.event.release.tag_name }}"
          npm run build

      - name: Upload build result to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/my-harmony-card.js
          asset_name: my-harmony-card.js
          tag: ${{ github.ref }}
          overwrite: true
