name: Validate
on:
  push:
    branches:
      - "master"
    paths:
      - "custom_components/**"
      - "hacs.json"
      - ".github/workflows/validate.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "custom_components/**"
      - "hacs.json"
      - ".github/workflows/validate.yml"
  workflow_dispatch:

