name: Validate HACS

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate HACS
        uses: "hacs/action@main"
        with:
          category: "plugin"
