name: "Validate"

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  hacs: # https://github.com/hacs/action
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write  # Berechtigung zum Lesen und Schreiben von Repository-Inhalten
      issues: write    # Berechtigung für Issues
      pull-requests: write # Berechtigung für Pull Requests
      packages: read   # Zugriff auf GitHub Packages
      actions: write   # Berechtigung für GitHub Actions
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4"

        - name: "Run HACS validation"
          uses: "hacs/action@main"
          with:
            category: "plugin"
            # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
            ignore: "brands"
